name: diss-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.12.8
  - seaborn=0.13.2
  - matplotlib=3.10.0
  - pandas=2.2.3
  - ipykernel=6.29.5
  - scikit-learn=1.6.1
