name: diss-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.8
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - xgboost=3.0.2
  - lightgbm=4.6.0
  - matplotlib=3.10.0
  - shap=0.47.2
